config/routes.rb
UrlCompresser::Application.routes.draw do

  root to: 'url_store#index'

  resources :url_store 
   
  match '/:token' => 'url_store#handle_url', as: :handle_url
  

end

app/models/audit.rb
class Audit < ActiveRecord::Base
  attr_accessible :remote_ip
  belongs_to :url_store
  
  validates_presence_of :remote_ip
end

app/models/url_store.rb
class UrlStore < ActiveRecord::Base
  attr_accessible :generic_url
  
  has_many :audits, :foreign_key => "url_id"

  validates_presence_of :generic_url
  validates_uniqueness_of :alias
  validates_format_of :generic_url, :with => /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/

  before_create :create_unique_alias

  def save_with_alias(options)
    self.transaction do
      self.generic_url = options[:generic_url]
      add_audit(options[:remote_ip]).save!
    end
    self
  end

  def link_to_display
    "http://localhost:3000/#{self.alias}"
  end
  
  def add_audit(remote_ip)
    self.audits << Audit.create!(remote_ip: remote_ip) 
    self   
  end

  private

  def create_unique_alias
    begin
      self.alias = SecureRandom.urlsafe_base64(4)
    end while self.class.exists?(alias: self.alias)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/url_store_controller.rb
class UrlStoreController < ApplicationController
  
  def index
    @urls = UrlStore.all
  end

  def new
    @url = UrlStore.new()
  end

  def create
    @url = UrlStore.new().save_with_alias(options)

    respond_to do |format|
      format.html {redirect_to url_store_index_path}
    end
  end
  
  def handle_url
    @url = UrlStore.find_by_alias(get_alias).add_audit(request.remote_ip)
    respond_to do |format|
      format.html { redirect_to @url.generic_url }
    end    
  end

  private

  def options
    unless params[:url_store][:generic_url].blank?
      return {generic_url: params[:url_store][:generic_url], remote_ip: request.remote_ip}
    end
    {}
  end
  
  def get_alias
    params[:token] unless params[:token].blank?
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.haml
%h4 List of saved urls

%ul
  - @urls.each do |url|
    %li
      = link_to url.link_to_display, handle_url_path(url.alias)

%div
  = button_to 'add one more url', new_url_store_path, method: 'get'

app/views/application/new.haml
%h4 Add a new url

%div
  = form_for @url, url: {action: :create} do |form|
    = form.text_field :generic_url
    = form.submit 'Compress'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlCompresser</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>